[pytest]
asyncio_mode=auto
asyncio_default_fixture_loop_scope=function
filterwarnings =
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning
    ignore:.*Pydantic V1 style.*:UserWarning
