CREATE TYPE public.permission AS ENUM (
  'user.create',
  'user.delete',
  'user.get',
  'user.update',
  'role.update',
  'role.create',
  'role.delete',
  'role.get',
  'role.permission.create',
  'role.permission.delete',
  'role.permission.get',
  'role.permission.update',
  'department.get',
  'department.create',
  'department.delete',
  'department.update',
  'worker.update',
  'worker.knowledge_base.update'
  );
-- create type public.app_role as enum ('super_admin', 'admin', 'moderator');

CREATE TABLE public.permission_description(
  id                SERIAL PRIMARY KEY,
  permission        public.permission NOT NULL,
  description       VARCHAR NOT NULL,
  permission_group  VARCHAR NOT NULL,
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP DEFAULT NOW()
);

CREATE TABLE public.role (
  id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name  VARCHAR NOT NULL,
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP DEFAULT NOW()
);


create table public.role_permissions (
  id          bigint generated by default as identity primary key,
  role_id     uuid references public.role on delete cascade not null,
  permission  public.permission not null,
  unique      (role_id, permission),
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP DEFAULT NOW()
);


CREATE TABLE public.department (
  id            SERIAL PRIMARY KEY,
  name          VARCHAR NOT NULL,
  description   VARCHAR NULL,
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP DEFAULT NOW()
);


ALTER TABLE auth.users
  ADD COLUMN department_id INTEGER REFERENCES public.department ON DELETE SET NULL;

ALTER TABLE auth.users
  ADD COLUMN role_access_id uuid REFERENCES public.role ON DELETE SET NULL;


CREATE TABLE public.worker (
  id            SERIAL PRIMARY KEY,
  name          VARCHAR NOT NULL,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);


CREATE TABLE public.department_available_worker (
  id              SERIAL PRIMARY KEY,
  worker_id       INTEGER REFERENCES public.worker ON DELETE CASCADE NOT NULL,
  department_id   INTEGER REFERENCES public.department ON DELETE CASCADE NOT NULL,
  unique          (worker_id, department_id),
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW()
);


CREATE TABLE public.user_assigned_worker (
  id              SERIAL PRIMARY KEY,
  user_id         uuid REFERENCES auth.users ON DELETE CASCADE,
  worker_id       INTEGER REFERENCES public.worker ON DELETE CASCADE,
  unique          (user_id, worker_id),
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW()
);

 -- Example: enable the "vector" extension.
create extension vector
with
  schema extensions;

-- create table public.user_roles (
--   id        bigint generated by default as identity primary key,
--   user_id   uuid references auth.users on delete cascade not null,
--   role_id   uuid references public.role on delete cascade not null,
--   unique    (user_id, role_id)
-- );
