apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRefName }}
    kind: {{ .Values.externalSecrets.secretStoreRefKind }}
  target:
    name: {{ .Values.externalSecrets.name }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.dataFrom.extract.key }}
